### PR TITLE
Changed usage of deprecated test class

### PR DESCRIPTION
**Pull request by bdunogier**
Use `RelationSearchBaseIntegrationTestTrait` instead of deprecated `RelationSearchBaseIntegrationTest`.

### CODE REVIEW

**Comment by andrerom** [comment]
I tought this was tested in https://github.com/ezsystems/ezpublish-kernel/commit/d962fe4531076add0727a23fd597bb4fc39de2ae. So left it as is here to make sure it continues to work. Still broken?

**Comment by andrerom** [comment]
tested -> fixed

**Comment by bdunogier** [comment]
> I tought this was tested in ezsystems/ezpublish-kernel@d962fe4. So left it as is here to make sure it continues to work.

I had missed that one indeed.

**Comment by bdunogier** [comment]
Restarted the jobs, it passed. Thank you for the heads up @andrerom.

**Pull request merged**
