### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by emodric**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | N/A
| **Type**           | Improvement
| **Target version** | `master`
| **BC breaks**      | yes
| **Doc needed**     | no

Migrates the package to eZ kernel 8.

**TODO**:
- [x] Implement feature / fix a bug.
- [x] Implement tests + specs and passing (`$ composer test`)
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by emodric** [comment]
Ping @andrerom @alongosz

**Comment by andrerom** [comment]
Hi,

for 2.0 we should fork this repo to ezcommunity so we can find someone in community willing to review and help out. Also to make it a bit more clear it's not supported from eZ directly.

**Comment by emodric** [comment]
Can we merge this first, and then do the move? It would help with testing eZ Platform v3 while proper support is established?

**Comment by andrerom** [comment]
well, on second look, given this does not rely on legacy or legacy bridge that is fine with me. Never know, might be we end up wanting to support 4.7/5.4 direct content migration to 3.0 as well at some point.

**Comment by andrerom** [comment]
(NB! I didn't review the code in detail, but looks about right. Feel free to merge.)

**Comment by emodric** [comment]
@alongosz Okay with you like this?

**Comment by emodric** [comment]
Thanks for the review @andrerom @alongosz !

**Pull request merged**
