### PR TITLE
EZP-29507: ezxmltext -> richtext conversion: width attribute in table|tr|th elements containing "px"

### PR DESCRIPTION
**Pull request by vidarl**
This one fixes [EZP-29507](https://jira.ez.no/browse/EZP-29507)

### CODE REVIEW

**Comment by vidarl** [comment]
review ping : Rewrote xslt as it turns out we can expect lot of other stuff as width value to (like `<table width="”100%”">`)

So, adding a whitelist and stripping away anything else

**Comment by andrerom** [comment]
@vidarl What is the outer translate() doing now?

**Comment by vidarl** [comment]
hehe.. This is a nice trick... With a single translate(), you'll only have a blacklist... I wanted a whiteliste of accepted characters..
So, the inner translate() removes any character we actually accept, what remains is all unwanted characters in @width. Those characters (and only those) are then removed by the outer translate()

**Comment by andrerom** [comment]
Oh, ok. Could you add a inline comment to explain it to avoid people having to look it up what happens when reading it?

**Comment by vidarl** [comment]
Ok, added an explanation in the first occurrence in the file

**Comment by andrerom** [comment]
+1

**Pull request merged**
