### PR TITLE
Add basic support for editing through eZ Platform Admin UI

### PR DESCRIPTION
**Pull request by emodric**
This just shows a text area box for editing the XML, nothing more, but it is more than enough at the moment.

### CODE REVIEW

**Comment by emodric** [comment]
You're right, `ezpublish.fieldType.ezxmltext.formMapper` service does require repo forms in basically any version, but I've added `^1.9 || ^2.0` to keep inline with required kernel version.

**Comment by andrerom** [comment]
Should btw legacy bridge 2.0 require this package to make things more clear? (legacy will need it so can make sense)

**Comment by emodric** [comment]
@andrerom Good idea! Do you want to bump master to 1.5 here and tag it, and I can require it in legacy bridge?

**Comment by andrerom** [comment]
done, 1.5.0-rc1 out

**Comment by emodric** [comment]
:+1: 

Added the require in https://github.com/ezsystems/LegacyBridge/pull/129

**Pull request merged**
